version: "3.4"

# Production environment override
services:
  php:
    image: back-end_php:latest
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
  pwa:
    image: back-end_pwa:latest
  caddy:
    image: back-end_caddy:latest
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY}
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
