api_platform:

    
    title: OrigamiLab
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            enabled: true
            enabled_parameter_name: pagination
            page_parameter_name: _page
            partial: false 
            partial_parameter_name: 'partial'
            

            