vich_uploader:
    db_driver: orm

    mappings:
        
        media_object:
            uri_prefix: '%env(VICH_UPLOADER_URI_PREFIX)%'
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        file_upload:
            uri_prefix: '%env(VICH_UPLOADER_URI_PREFIX)%'
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
