apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lama
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = "lama.origamilab.ch") {
          return 301 https://www.baselland.ch/politik-und-behorden/direktionen/volkswirtschafts-und-gesundheitsdirektion/amt-fur-gesundheit/medizinische-dienste/kantonsarztlicher-dienst/aktuelles/massentest;
      }
spec:
  tls:
    - hosts:
        - lama.origamilab.ch
      secretName: lamafe-tls
  rules:
    - host: lama.origamilab.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 3000