apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-public-media-pv
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: scw-bssd
  csi:
    driver: csi.scaleway.com
    volumeHandle: 75c68b08-af30-4a08-9d82-23c6f4c25631


 
  
