apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistenVolume.name | quote }}
spec:
  capacity:
    storage: {{ .Values.persistenVolume.capacity | quote }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistenVolume.accessModes | quote }}
  storageClassName: efs-sc
  csi:
    driver: {{ .Values.persistenVolume.driver | quote }}
    volumeHandle: {{ .Values.persistenVolume.volumeId | quote }}