apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistenVolume.name | quote }}
spec:
  capacity:
    storage: {{ .Values.persistenVolume.capacity | quote }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistenVolume.accessModes | quote }}
  storageClassName: scw-bssd-retain
  csi:
    driver: {{ .Values.persistenVolume.driver | quote }}
    volumeHandle: {{ .Values.persistenVolume.volumeId | quote }}
  claimRef:
    name: php-public-media-pvc
    namespace: default
