apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistenVolume.name | quote }}
spec:
  capacity:
    storage: {{ .Values.persistenVolume.capacity | quote }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistenVolume.accessModes | quote }}
  storageClassName: {{ .Values.persistenVolume.storageClassName | quote }}
  csi:
    driver: {{ .Values.persistenVolume.driver | quote }}
    volumeHandle: c058fe12-ad7f-4fdf-b676-50e4ade7b303
    volumeHandle: {{ .Values.persistenVolume.volumeId | quote }}
  
