name: dev
on: 
  #workflow_dispatch
  push:
    branches:
      - develop

env:
  IMAGE_PHP: ${{ secrets.DOCKER_REGISTRY }}/dev-back-end_php
  IMAGE_CADDY: ${{ secrets.DOCKER_REGISTRY }}/dev-back-end_caddy
  IMAGE_PWA: ${{ secrets.DOCKER_REGISTRY }}/dev-back-end_pwa
  TAG: latest

jobs:
  deploy:
    environment:
      name: dev
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Config
        env:
          HELM_VALUES: ${{ secrets.DEV_HELM_VALUES }}
        shell: bash
        run: 'echo "$HELM_VALUES" > ./values.yaml'



      - name: Deploy
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: |
            helm dependency update helm/api-platform
            helm uninstall cobalt-back-end
            helm install cobalt-back-end ./helm/api-platform --namespace=default -f ./values.yaml

