name: prod
on: 
  workflow_dispatch
  # push:
  #   branches:
  #     - master

env:
  IMAGE_PHP: ${{ secrets.DOCKER_REGISTRY }}/cobalt-back-end_php
  IMAGE_CADDY: ${{ secrets.DOCKER_REGISTRY }}/cobalt-back-end_caddy
  IMAGE_PWA: ${{ secrets.DOCKER_REGISTRY }}/cobalt-back-end_pwa
  TAG: latest

jobs:
  deploy:
    environment:
      name: prod
      url: https://api.cobalt.origamilab.ch
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Config
        env:
          HELM_VALUES: ${{ secrets.HELM_VALUES }}
        shell: bash
        run: 'echo "$HELM_VALUES" > ./values.yaml'

      - name: Build images
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml build --no-cache php
          docker tag cobalt-back-end_php:latest $IMAGE_PHP:$TAG
          docker tag cobalt-back-end_caddy:latest $IMAGE_CADDY:$TAG
          docker tag cobalt-back-end_pwa:latest $IMAGE_PWA:$TAG

      - name: Push images
        run: |
          docker login ${{ secrets.DOCKER_REGISTRY }} -u nologin -p ${{ secrets.SCW_SECRET_KEY }}
          docker push $IMAGE_PHP:$TAG
          docker push $IMAGE_CADDY:$TAG
          docker push $IMAGE_PWA:$TAG

      - name: Deploy
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: |
            helm dependency update helm/api-platform
            helm uninstall cobalt-back-end
            helm install cobalt-back-end ./helm/api-platform --namespace=default -f ./values.yaml

